In [1]:
import os
import pandas as pd

In [2]:
# Path to the csv's
path_data_2015 = "Resources/raw_data/2015.csv"
path_data_2016 = "Resources/raw_data/2016.csv"
path_data_2017 = "Resources/raw_data/2017.csv"
path_data_2018 = "Resources/raw_data/2018.csv"
path_data_2019 = "Resources/raw_data/2019.csv"
path_countries_data="Resources/raw_data/countries.csv"
path_years_data="Resources/raw_data/years.csv"
path_ctry_rgn_data="Resources/raw_data/country_region.csv"
path_worldmap_data="Resources/raw_data/data_worldmap.csv"

In [3]:
# Reading csv ->df
data_2015_df = pd.read_csv(path_data_2015)
data_2016_df = pd.read_csv(path_data_2016)
data_2017_df = pd.read_csv(path_data_2017)
data_2018_df = pd.read_csv(path_data_2018)
data_2019_df = pd.read_csv(path_data_2019)

countries_df=pd.read_csv(path_countries_data)
years_df=pd.read_csv(path_years_data)
ctry_rgn_df=pd.read_csv(path_ctry_rgn_data)
worldmap_data_df=pd.read_csv(path_worldmap_data)

In [4]:
#Add region columns to 2017,2018 and 2019 df's
data_2017_df['region']=""
data_2018_df['region']=""
data_2019_df['region']=""

In [5]:
# Drop the unnecessary columns from 2015,2016,2017
data_2015_df.drop(['Standard Error', 'Family'], axis=1, inplace=True)
data_2016_df.drop(['Lower Confidence Interval', 'Upper Confidence Interval','Family'], axis=1, inplace=True)
data_2017_df.drop(['Whisker.high', 'Whisker.low','Family',], axis=1, inplace=True)

In [6]:
#Rename the columns
data_2015_df.columns = ['country', 'region', 'rank','score','gdp',
                        'health_life_expectancy','freedom','perceptions_of_corruption',
                       'generosity','dystopia_residual']

data_2016_df.columns = ['country', 'region', 'rank','score','gdp',
                        'health_life_expectancy','freedom','perceptions_of_corruption',
                       'generosity','dystopia_residual']

data_2017_df.columns = ['country','rank','score','gdp',
                        'health_life_expectancy','freedom','generosity',
                          'perceptions_of_corruption', 'dystopia_residual','region']

data_2018_df.columns = ['rank','country','score','gdp','social_support',
                        'health_life_expectancy','freedom','generosity',
                          'perceptions_of_corruption','region']

data_2019_df.columns = ['rank','country','score','gdp','social_support',
                        'health_life_expectancy','freedom','generosity',
                          'perceptions_of_corruption','region']

In [7]:
# Rearrange columns
data_2015_df = data_2015_df[['rank','country','region','score','gdp',
                             'health_life_expectancy','freedom',
                             'perceptions_of_corruption','generosity','dystopia_residual']]

data_2016_df = data_2016_df[['rank','country','region','score','gdp',
                             'health_life_expectancy','freedom',
                             'perceptions_of_corruption','generosity','dystopia_residual']]

data_2017_df = data_2017_df[['rank','country','region','score','gdp',
                             'health_life_expectancy','freedom',
                             'perceptions_of_corruption','generosity','dystopia_residual']]

data_2018_df = data_2018_df[['rank','country','region','score','gdp',
                             'health_life_expectancy','freedom',
                             'perceptions_of_corruption','generosity','social_support']]

data_2019_df = data_2019_df[['rank','country','region','score','gdp',
                             'health_life_expectancy','freedom',
                             'perceptions_of_corruption','generosity','social_support']]

In [8]:
data_2015_df.head()
data_2016_df.head()
data_2017_df.head()
data_2018_df.head()
data_2019_df.head()

,rank,country,region,score,gdp,health_life_expectancy,freedom,perceptions_of_corruption,generosity,social_support
0,1,Finland,,7.769,1.340,0.986,0.596,0.393,0.153,1.587
1,2,Denmark,,7.600,1.383,0.996,0.592,0.410,0.252,1.573
2,3,Norway,,7.554,1.488,1.028,0.603,0.341,0.271,1.582
3,4,Iceland,,7.494,1.380,1.026,0.591,0.118,0.354,1.624
4,5,Netherlands,,7.488,1.396,0.999,0.557,0.298,0.322,1.522

In [9]:
ctry_rgn_df.head()

       country                           region
0  Afghanistan                    Southern Asia
1      Albania       Central and Eastern Europe
2      Algeria  Middle East and Northern Africa
3       Angola               Sub-Saharan Africa
4    Argentina      Latin America and Caribbean

In [10]:
# Populating Region column to 2017,2018 and 2019 df
ctry_rgn_dict = dict()
for index,row in ctry_rgn_df.iterrows() :
    country_name = row['country']
    region = row['region']
    ctry_rgn_dict[country_name] = region
ctry_rgn_dict

{'Afghanistan': 'Southern Asia',
 'Albania': 'Central and Eastern Europe',
 'Algeria': 'Middle East and Northern Africa',
 'Angola': 'Sub-Saharan Africa',
 'Argentina': 'Latin America and Caribbean',
 'Armenia': 'Central and Eastern Europe',
 'Australia': 'Australia and New Zealand',
 'Austria': 'Western Europe',
 'Azerbaijan': 'Central and Eastern Europe',
 'Bahrain': 'Middle East and Northern Africa',
 'Bangladesh': 'Southern Asia',
 'Belarus': 'Central and Eastern Europe',
 'Belgium': 'Western Europe',
 'Belize': 'Latin America and Caribbean',
 'Benin': 'Sub-Saharan Africa',
 'Bhutan': 'Southern Asia',
 'Bolivia': 'Latin America and Caribbean',
 'Bosnia and Herzegovina': 'Central and Eastern Europe',
 'Botswana': 'Sub-Saharan Africa',
 'Brazil': 'Latin America and Caribbean',
 'Bulgaria': 'Central and Eastern Europe',
 'Burkina Faso': 'Sub-Saharan Africa',
 'Burundi': 'Sub-Saharan Africa',
 'Cambodia': 'Southeastern Asia',
 'Cameroon': 'Sub-Saharan Africa',
 'Canada': 'North America',
 'Central African Republic': 'Sub-Saharan Africa',
 'Chad': 'Sub-Saharan Africa',
 'Chile': 'Latin America and Caribbean',
 'China': 'Eastern Asia',
 'Colombia': 'Latin America and Caribbean',
 'Comoros': 'Sub-Saharan Africa',
 'Congo (Brazzaville)': 'Sub-Saharan Africa',
 'Congo (Kinshasa)': 'Sub-Saharan Africa',
 'Costa Rica': 'Latin America and Caribbean',
 'Croatia': 'Central and Eastern Europe',
 'Cyprus': 'Western Europe',
 'Czech Republic': 'Central and Eastern Europe',
 'Denmark': 'Western Europe',
 'Djibouti': 'Sub-Saharan Africa',
 'Dominican Republic': 'Latin America and Caribbean',
 'Ecuador': 'Latin America and Caribbean',
 'Egypt': 'Middle East and Northern Africa',
 'El Salvador': 'Latin America and Caribbean',
 'Estonia': 'Central and Eastern Europe',
 'Ethiopia': 'Sub-Saharan Africa',
 'Finland': 'Western Europe',
 'France': 'Western Europe',
 'Gabon': 'Sub-Saharan Africa',
 'Gambia': 'Sub-Saharan Africa',
 'Georgia': 'Central and Eastern Europe',
 'Germany': 'Western Europe',
 'Ghana': 'Sub-Saharan Africa',
 'Greece': 'Western Europe',
 'Guatemala': 'Latin America and Caribbean',
 'Guinea': 'Sub-Saharan Africa',
 'Haiti': 'Latin America and Caribbean',
 'Honduras': 'Latin America and Caribbean',
 'Hong Kong': 'Eastern Asia',
 'Hong Kong S.A.R., China': 'Eastern Asia',
 'Hungary': 'Central and Eastern Europe',
 'Iceland': 'Western Europe',
 'India': 'Southern Asia',
 'Indonesia': 'Southeastern Asia',
 'Iran': 'Middle East and Northern Africa',
 'Iraq': 'Middle East and Northern Africa',
 'Ireland': 'Western Europe',
 'Israel': 'Middle East and Northern Africa',
 'Italy': 'Western Europe',
 'Ivory Coast': 'Sub-Saharan Africa',
 'Jamaica': 'Latin America and Caribbean',
 'Japan': 'Eastern Asia',
 'Jordan': 'Middle East and Northern Africa',
 'Kazakhstan': 'Central and Eastern Europe',
 'Kenya': 'Sub-Saharan Africa',
 'Kosovo': 'Central and Eastern Europe',
 'Kuwait': 'Middle East and Northern Africa',
 'Kyrgyzstan': 'Central and Eastern Europe',
 'Laos': 'Southeastern Asia',
 'Latvia': 'Central and Eastern Europe',
 'Lebanon': 'Middle East and Northern Africa',
 'Lesotho': 'Sub-Saharan Africa',
 'Liberia': 'Sub-Saharan Africa',
 'Libya': 'Middle East and Northern Africa',
 'Lithuania': 'Central and Eastern Europe',
 'Luxembourg': 'Western Europe',
 'Macedonia': 'Central and Eastern Europe',
 'Madagascar': 'Sub-Saharan Africa',
 'Malawi': 'Sub-Saharan Africa',
 'Malaysia': 'Southeastern Asia',
 'Mali': 'Sub-Saharan Africa',
 'Malta': 'Western Europe',
 'Mauritania': 'Sub-Saharan Africa',
 'Mauritius': 'Sub-Saharan Africa',
 'Mexico': 'Latin America and Caribbean',
 'Moldova': 'Central and Eastern Europe',
 'Mongolia': 'Eastern Asia',
 'Montenegro': 'Central and Eastern Europe',
 'Morocco': 'Middle East and Northern Africa',
 'Mozambique': 'Sub-Saharan Africa',
 'Myanmar': 'Southeastern Asia',
 'Namibia': 'Sub-Saharan Africa',
 'Nepal': 'Southern Asia',
 'Netherlands': 'Western Europe',
 'New Zealand': 'Australia and New Zealand',
 'Nicaragua': 'Latin America and Caribbean',
 'Niger': 'Sub-Saharan Africa',
 'Nigeria': 'Sub-Saharan Africa',
 'North Cyprus': 'Western Europe',
 'North Macedonia': 'Central and Eastern Europe',
 'Northern Cyprus': 'Middle East and Northern Africa',
 'Norway': 'Western Europe',
 'Oman': 'Middle East and Northern Africa',
 'Pakistan': 'Southern Asia',
 'Palestinian Territories': 'Middle East and Northern Africa',
 'Panama': 'Latin America and Caribbean',
 'Paraguay': 'Latin America and Caribbean',
 'Peru': 'Latin America and Caribbean',
 'Philippines': 'Southeastern Asia',
 'Poland': 'Central and Eastern Europe',
 'Portugal': 'Western Europe',
 'Puerto Rico': 'Latin America and Caribbean',
 'Qatar': 'Middle East and Northern Africa',
 'Romania': 'Central and Eastern Europe',
 'Russia': 'Central and Eastern Europe',
 'Rwanda': 'Sub-Saharan Africa',
 'Saudi Arabia': 'Middle East and Northern Africa',
 'Senegal': 'Sub-Saharan Africa',
 'Serbia': 'Central and Eastern Europe',
 'Sierra Leone': 'Sub-Saharan Africa',
 'Singapore': 'Southeastern Asia',
 'Slovakia': 'Central and Eastern Europe',
 'Slovenia': 'Central and Eastern Europe',
 'Somalia': 'Sub-Saharan Africa',
 'Somaliland region': 'Sub-Saharan Africa',
 'South Africa': 'Sub-Saharan Africa',
 'South Korea': 'Eastern Asia',
 'South Sudan': 'Sub-Saharan Africa',
 'Spain': 'Western Europe',
 'Sri Lanka': 'Southern Asia',
 'Sudan': 'Sub-Saharan Africa',
 'Suriname': 'Latin America and Caribbean',
 'Swaziland': 'Sub-Saharan Africa',
 'Sweden': 'Western Europe',
 'Switzerland': 'Western Europe',
 'Syria': 'Middle East and Northern Africa',
 'Taiwan': 'Eastern Asia',
 'Taiwan Province of China': 'Eastern Asia',
 'Tajikistan': 'Central and Eastern Europe',
 'Tanzania': 'Sub-Saharan Africa',
 'Thailand': 'Southeastern Asia',
 'Togo': 'Sub-Saharan Africa',
 'Trinidad & Tobago': 'Latin America and Caribbean',
 'Trinidad and Tobago': 'Latin America and Caribbean',
 'Tunisia': 'Middle East and Northern Africa',
 'Turkey': 'Middle East and Northern Africa',
 'Turkmenistan': 'Central and Eastern Europe',
 'Uganda': 'Sub-Saharan Africa',
 'Ukraine': 'Central and Eastern Europe',
 'United Arab Emirates': 'Middle East and Northern Africa',
 'United Kingdom': 'Western Europe',
 'United States': 'North America',
 'Uruguay': 'Latin America and Caribbean',
 'Uzbekistan': 'Central and Eastern Europe',
 'Venezuela': 'Latin America and Caribbean',
 'Vietnam': 'Southeastern Asia',
 'Yemen': 'Middle East and Northern Africa',
 'Zambia': 'Sub-Saharan Africa',
 'Zimbabwe': 'Sub-Saharan Africa'}

In [11]:
# Function to populate region 2017,2018 and 2019 df
def add_region(df):
    for index,row in df.iterrows() :
        try:
            df.loc[index,'region'] = ctry_rgn_dict.get(row['country'])
        except:
            continue

In [12]:
# Function call to populate the region 2017,2018 and 2019 df
add_region(data_2017_df)
add_region(data_2018_df)
add_region(data_2019_df)

In [13]:
data_2015_df.head()
data_2016_df.head()
data_2017_df.head()
data_2018_df.head()
data_2019_df.head()

,rank,country,region,score,gdp,health_life_expectancy,freedom,perceptions_of_corruption,generosity,social_support
0,1,Finland,Western Europe,7.769,1.340,0.986,0.596,0.393,0.153,1.587
1,2,Denmark,Western Europe,7.600,1.383,0.996,0.592,0.410,0.252,1.573
2,3,Norway,Western Europe,7.554,1.488,1.028,0.603,0.341,0.271,1.582
3,4,Iceland,Western Europe,7.494,1.380,1.026,0.591,0.118,0.354,1.624
4,5,Netherlands,Western Europe,7.488,1.396,0.999,0.557,0.298,0.322,1.522

In [14]:
data_2015_df.to_csv("Resources/cleansed_data/clean_data15.csv",index=False,header=True,encoding='utf-8-sig')
data_2016_df.to_csv("Resources/cleansed_data/clean_data16.csv",index=False,header=True,encoding='utf-8-sig')
data_2017_df.to_csv("Resources/cleansed_data/clean_data17.csv",index=False,header=True,encoding='utf-8-sig')
data_2018_df.to_csv("Resources/cleansed_data/clean_data18.csv",index=False,header=True,encoding='utf-8-sig')
data_2019_df.to_csv("Resources/cleansed_data/clean_data19.csv",index=False,header=True,encoding='utf-8-sig')

In [15]:
import pandas as pd
import pymongo
import json
import os
 
mng_client = pymongo.MongoClient('localhost', 27017)
mng_db = mng_client['project2_db']

# Import 2015 data to mongodb
collection_name='2015_data'
db_cm = mng_db[collection_name]
# file_res = os.path.join('Resources/clean_data15.csv')
data = pd.read_csv('Resources/cleansed_data/clean_data15.csv')
data_json = json.loads(data.to_json(orient='records')) 
db_cm.remove()
db_cm.insert(data_json)

# Import 2017 data to mongodb
collection_name='2016_data'
db_cm = mng_db[collection_name]
# file_res = os.path.join('Resources/clean_data15.csv')
data = pd.read_csv('Resources/cleansed_data/clean_data16.csv')
data_json = json.loads(data.to_json(orient='records')) 
db_cm.remove()
db_cm.insert(data_json)

# Import 2015 data to mongodb
collection_name='2017_data'
db_cm = mng_db[collection_name]
# file_res = os.path.join('Resources/clean_data15.csv')
data = pd.read_csv('Resources/cleansed_data/clean_data17.csv')
data_json = json.loads(data.to_json(orient='records')) 
db_cm.remove()
db_cm.insert(data_json)

# Import 2015 data to mongodb
collection_name='2018_data'
db_cm = mng_db[collection_name]
# file_res = os.path.join('Resources/clean_data15.csv')
data = pd.read_csv('Resources/cleansed_data/clean_data18.csv')
data_json = json.loads(data.to_json(orient='records')) 
db_cm.remove()
db_cm.insert(data_json)

# Import 2015 data to mongodb
collection_name='2019_data'
db_cm = mng_db[collection_name]
# file_res = os.path.join('Resources/clean_data15.csv')
data = pd.read_csv('Resources/cleansed_data/clean_data19.csv')
data_json = json.loads(data.to_json(orient='records')) 
db_cm.remove()
db_cm.insert(data_json)


# Import 2016 data to mongodb
collection_name='countries'
db_cm = mng_db[collection_name]
# file_res = os.path.join('Resources/clean_data15.csv')
data = pd.read_csv('Resources/raw_data/countries.csv')
data_json = json.loads(data.to_json(orient='records')) 
db_cm.remove()
db_cm.insert(data_json)


# Import 2016 data to mongodb
collection_name='years'
db_cm = mng_db[collection_name]
# file_res = os.path.join('Resources/clean_data15.csv')
data = pd.read_csv('Resources/raw_data/years.csv')
data_json = json.loads(data.to_json(orient='records')) 
db_cm.remove()
db_cm.insert(data_json)


# Import 2016 data to mongodb
collection_name='worldmap_data'
db_cm = mng_db[collection_name]
# file_res = os.path.join('Resources/clean_data15.csv')
data = pd.read_csv('Resources/raw_data/data_worldmap.csv')
data_json = json.loads(data.to_json(orient='records')) 
db_cm.remove()
db_cm.insert(data_json)

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:15: DeprecationWarning: remove is deprecated. Use delete_one or delete_many instead.
  from ipykernel import kernelapp as app
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
  app.launch_new_instance()
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:24: DeprecationWarning: remove is deprecated. Use delete_one or delete_many instead.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:25: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:33: DeprecationWarning: remove is deprecated. Use delete_one or delete_many instead.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:34: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:42: DeprecationWarning: remove is deprecated. Use delete_one or delete_many instead.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:43: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:51: DeprecationWarning: remove is deprecated. Use delete_one or delete_many instead.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:52: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:61: DeprecationWarning: remove is deprecated. Use delete_one or delete_many instead.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:62: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:71: DeprecationWarning: remove is deprecated. Use delete_one or delete_many instead.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:72: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:81: DeprecationWarning: remove is deprecated. Use delete_one or delete_many instead.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:82: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.

[ObjectId('5e3496b661b63ef1e74a79dc'),
 ObjectId('5e3496b661b63ef1e74a79dd'),
 ObjectId('5e3496b661b63ef1e74a79de'),
 ObjectId('5e3496b661b63ef1e74a79df'),
 ObjectId('5e3496b661b63ef1e74a79e0'),
 ObjectId('5e3496b661b63ef1e74a79e1'),
 ObjectId('5e3496b661b63ef1e74a79e2'),
 ObjectId('5e3496b661b63ef1e74a79e3'),
 ObjectId('5e3496b661b63ef1e74a79e4'),
 ObjectId('5e3496b661b63ef1e74a79e5'),
 ObjectId('5e3496b661b63ef1e74a79e6'),
 ObjectId('5e3496b661b63ef1e74a79e7'),
 ObjectId('5e3496b661b63ef1e74a79e8'),
 ObjectId('5e3496b661b63ef1e74a79e9'),
 ObjectId('5e3496b661b63ef1e74a79ea'),
 ObjectId('5e3496b661b63ef1e74a79eb'),
 ObjectId('5e3496b661b63ef1e74a79ec'),
 ObjectId('5e3496b661b63ef1e74a79ed'),
 ObjectId('5e3496b661b63ef1e74a79ee'),
 ObjectId('5e3496b661b63ef1e74a79ef'),
 ObjectId('5e3496b661b63ef1e74a79f0'),
 ObjectId('5e3496b661b63ef1e74a79f1'),
 ObjectId('5e3496b661b63ef1e74a79f2'),
 ObjectId('5e3496b661b63ef1e74a79f3'),
 ObjectId('5e3496b661b63ef1e74a79f4'),
 ObjectId('5e3496b661b63ef1e74a79f5'),
 ObjectId('5e3496b661b63ef1e74a79f6'),
 ObjectId('5e3496b661b63ef1e74a79f7'),
 ObjectId('5e3496b661b63ef1e74a79f8'),
 ObjectId('5e3496b661b63ef1e74a79f9'),
 ObjectId('5e3496b661b63ef1e74a79fa'),
 ObjectId('5e3496b661b63ef1e74a79fb'),
 ObjectId('5e3496b661b63ef1e74a79fc'),
 ObjectId('5e3496b661b63ef1e74a79fd'),
 ObjectId('5e3496b661b63ef1e74a79fe'),
 ObjectId('5e3496b661b63ef1e74a79ff'),
 ObjectId('5e3496b661b63ef1e74a7a00'),
 ObjectId('5e3496b661b63ef1e74a7a01'),
 ObjectId('5e3496b661b63ef1e74a7a02'),
 ObjectId('5e3496b661b63ef1e74a7a03'),
 ObjectId('5e3496b661b63ef1e74a7a04'),
 ObjectId('5e3496b661b63ef1e74a7a05'),
 ObjectId('5e3496b661b63ef1e74a7a06'),
 ObjectId('5e3496b661b63ef1e74a7a07'),
 ObjectId('5e3496b661b63ef1e74a7a08'),
 ObjectId('5e3496b661b63ef1e74a7a09'),
 ObjectId('5e3496b661b63ef1e74a7a0a'),
 ObjectId('5e3496b661b63ef1e74a7a0b'),
 ObjectId('5e3496b661b63ef1e74a7a0c'),
 ObjectId('5e3496b661b63ef1e74a7a0d'),
 ObjectId('5e3496b661b63ef1e74a7a0e'),
 ObjectId('5e3496b661b63ef1e74a7a0f'),
 ObjectId('5e3496b661b63ef1e74a7a10'),
 ObjectId('5e3496b661b63ef1e74a7a11'),
 ObjectId('5e3496b661b63ef1e74a7a12'),
 ObjectId('5e3496b661b63ef1e74a7a13'),
 ObjectId('5e3496b661b63ef1e74a7a14'),
 ObjectId('5e3496b661b63ef1e74a7a15'),
 ObjectId('5e3496b661b63ef1e74a7a16'),
 ObjectId('5e3496b661b63ef1e74a7a17'),
 ObjectId('5e3496b661b63ef1e74a7a18'),
 ObjectId('5e3496b661b63ef1e74a7a19'),
 ObjectId('5e3496b661b63ef1e74a7a1a'),
 ObjectId('5e3496b661b63ef1e74a7a1b'),
 ObjectId('5e3496b661b63ef1e74a7a1c'),
 ObjectId('5e3496b661b63ef1e74a7a1d'),
 ObjectId('5e3496b661b63ef1e74a7a1e'),
 ObjectId('5e3496b661b63ef1e74a7a1f'),
 ObjectId('5e3496b661b63ef1e74a7a20'),
 ObjectId('5e3496b661b63ef1e74a7a21'),
 ObjectId('5e3496b661b63ef1e74a7a22'),
 ObjectId('5e3496b661b63ef1e74a7a23'),
 ObjectId('5e3496b661b63ef1e74a7a24'),
 ObjectId('5e3496b661b63ef1e74a7a25'),
 ObjectId('5e3496b661b63ef1e74a7a26'),
 ObjectId('5e3496b661b63ef1e74a7a27'),
 ObjectId('5e3496b661b63ef1e74a7a28'),
 ObjectId('5e3496b661b63ef1e74a7a29'),
 ObjectId('5e3496b661b63ef1e74a7a2a'),
 ObjectId('5e3496b661b63ef1e74a7a2b'),
 ObjectId('5e3496b661b63ef1e74a7a2c'),
 ObjectId('5e3496b661b63ef1e74a7a2d'),
 ObjectId('5e3496b661b63ef1e74a7a2e'),
 ObjectId('5e3496b661b63ef1e74a7a2f'),
 ObjectId('5e3496b661b63ef1e74a7a30'),
 ObjectId('5e3496b661b63ef1e74a7a31'),
 ObjectId('5e3496b661b63ef1e74a7a32'),
 ObjectId('5e3496b661b63ef1e74a7a33'),
 ObjectId('5e3496b661b63ef1e74a7a34'),
 ObjectId('5e3496b661b63ef1e74a7a35'),
 ObjectId('5e3496b661b63ef1e74a7a36'),
 ObjectId('5e3496b661b63ef1e74a7a37'),
 ObjectId('5e3496b661b63ef1e74a7a38'),
 ObjectId('5e3496b661b63ef1e74a7a39'),
 ObjectId('5e3496b661b63ef1e74a7a3a'),
 ObjectId('5e3496b661b63ef1e74a7a3b'),
 ObjectId('5e3496b661b63ef1e74a7a3c'),
 ObjectId('5e3496b661b63ef1e74a7a3d'),
 ObjectId('5e3496b661b63ef1e74a7a3e'),
 ObjectId('5e3496b661b63ef1e74a7a3f'),
 ObjectId('5e3496b661b63ef1e74a7a40'),
 ObjectId('5e3496b661b63ef1e74a7a41'),
 ObjectId('5e3496b661b63ef1e74a7a42'),
 ObjectId('5e3496b661b63ef1e74a7a43'),
 ObjectId('5e3496b661b63ef1e74a7a44'),
 ObjectId('5e3496b661b63ef1e74a7a45'),
 ObjectId('5e3496b661b63ef1e74a7a46'),
 ObjectId('5e3496b661b63ef1e74a7a47'),
 ObjectId('5e3496b661b63ef1e74a7a48'),
 ObjectId('5e3496b661b63ef1e74a7a49'),
 ObjectId('5e3496b661b63ef1e74a7a4a'),
 ObjectId('5e3496b661b63ef1e74a7a4b'),
 ObjectId('5e3496b661b63ef1e74a7a4c'),
 ObjectId('5e3496b661b63ef1e74a7a4d'),
 ObjectId('5e3496b661b63ef1e74a7a4e'),
 ObjectId('5e3496b661b63ef1e74a7a4f'),
 ObjectId('5e3496b661b63ef1e74a7a50'),
 ObjectId('5e3496b661b63ef1e74a7a51'),
 ObjectId('5e3496b661b63ef1e74a7a52'),
 ObjectId('5e3496b661b63ef1e74a7a53'),
 ObjectId('5e3496b661b63ef1e74a7a54'),
 ObjectId('5e3496b661b63ef1e74a7a55'),
 ObjectId('5e3496b661b63ef1e74a7a56'),
 ObjectId('5e3496b661b63ef1e74a7a57'),
 ObjectId('5e3496b661b63ef1e74a7a58'),
 ObjectId('5e3496b661b63ef1e74a7a59'),
 ObjectId('5e3496b661b63ef1e74a7a5a'),
 ObjectId('5e3496b661b63ef1e74a7a5b'),
 ObjectId('5e3496b661b63ef1e74a7a5c'),
 ObjectId('5e3496b661b63ef1e74a7a5d'),
 ObjectId('5e3496b661b63ef1e74a7a5e'),
 ObjectId('5e3496b661b63ef1e74a7a5f'),
 ObjectId('5e3496b661b63ef1e74a7a60'),
 ObjectId('5e3496b661b63ef1e74a7a61'),
 ObjectId('5e3496b661b63ef1e74a7a62'),
 ObjectId('5e3496b661b63ef1e74a7a63'),
 ObjectId('5e3496b661b63ef1e74a7a64'),
 ObjectId('5e3496b661b63ef1e74a7a65'),
 ObjectId('5e3496b661b63ef1e74a7a66'),
 ObjectId('5e3496b661b63ef1e74a7a67'),
 ObjectId('5e3496b661b63ef1e74a7a68'),
 ObjectId('5e3496b661b63ef1e74a7a69'),
 ObjectId('5e3496b661b63ef1e74a7a6a'),
 ObjectId('5e3496b661b63ef1e74a7a6b'),
 ObjectId('5e3496b661b63ef1e74a7a6c'),
 ObjectId('5e3496b661b63ef1e74a7a6d'),
 ObjectId('5e3496b661b63ef1e74a7a6e'),
 ObjectId('5e3496b661b63ef1e74a7a6f'),
 ObjectId('5e3496b661b63ef1e74a7a70'),
 ObjectId('5e3496b661b63ef1e74a7a71'),
 ObjectId('5e3496b661b63ef1e74a7a72'),
 ObjectId('5e3496b661b63ef1e74a7a73'),
 ObjectId('5e3496b661b63ef1e74a7a74'),
 ObjectId('5e3496b661b63ef1e74a7a75'),
 ObjectId('5e3496b661b63ef1e74a7a76'),
 ObjectId('5e3496b661b63ef1e74a7a77'),
 ObjectId('5e3496b661b63ef1e74a7a78'),
 ObjectId('5e3496b661b63ef1e74a7a79'),
 ObjectId('5e3496b661b63ef1e74a7a7a'),
 ObjectId('5e3496b661b63ef1e74a7a7b'),
 ObjectId('5e3496b661b63ef1e74a7a7c'),
 ObjectId('5e3496b661b63ef1e74a7a7d'),
 ObjectId('5e3496b661b63ef1e74a7a7e'),
 ObjectId('5e3496b661b63ef1e74a7a7f'),
 ObjectId('5e3496b661b63ef1e74a7a80'),
 ObjectId('5e3496b661b63ef1e74a7a81'),
 ObjectId('5e3496b661b63ef1e74a7a82'),
 ObjectId('5e3496b661b63ef1e74a7a83'),
 ObjectId('5e3496b661b63ef1e74a7a84')]